"""Growatt Sensor definitions for the Inverter type."""
from __future__ import annotations

from homeassistant.components.number import NumberDeviceClass, NumberMode
from homeassistant.components.sensor import (
    SensorDeviceClass,
    SensorStateClass,
)
from homeassistant.const import (
    EntityCategory,
    UnitOfEnergy,
    UnitOfPower,
    PERCENTAGE,
)
from .number_entity_description import GrowattNumberEntityDescription
from .select_entity_description import GrowattSelectEntityDescription
from .sensor_entity_description import GrowattSensorEntityDescription
from .switch_entity_description import GrowattSwitchEntityDescription
from .time_entity_description import GrowattTimeEntityDescription

from ..API.device_type.base import (
    ATTR_AC_CHARGE_ENABLED,
    ATTR_DISCHARGE_POWER_LIMIT_RATE,
    ATTR_CHARGE_POWER_LIMIT_RATE,
    ATTR_DISCHARGE_STOP_SOC_PERCENT_OFFGRID,
    ATTR_DISCHARGE_STOP_SOC_PERCENT_ONGRID,
    ATTR_CHARGE_STOP_SOC_PERCENT,
    ATTR_CHARGE_DISCHARGE_PERIOD_1,
    ATTR_CHARGE_DISCHARGE_PERIOD_2,
    ATTR_CHARGE_DISCHARGE_PERIOD_3,
    ATTR_CHARGE_DISCHARGE_PERIOD_4,
    ATTR_CHARGE_DISCHARGE_PERIOD_5,
    ATTR_CHARGE_DISCHARGE_PERIOD_6,
    ATTR_CHARGE_DISCHARGE_PERIOD_7,
    ATTR_CHARGE_DISCHARGE_PERIOD_8,
    ATTR_CHARGE_DISCHARGE_PERIOD_9,
    ATTR_PRIORITY_MODE,
    ATTR_SOC_PERCENTAGE,
    ATTR_DISCHARGE_POWER,
    ATTR_CHARGE_POWER,
    ATTR_POWER_TO_USER,
    ATTR_POWER_TO_GRID,
    ATTR_POWER_USER_LOAD,
    ATTR_ENERGY_TO_USER_TODAY,
    ATTR_ENERGY_TO_USER_TOTAL,
    ATTR_ENERGY_TO_GRID_TODAY,
    ATTR_ENERGY_TO_GRID_TOTAL,
    ATTR_DISCHARGE_ENERGY_TODAY,
    ATTR_DISCHARGE_ENERGY_TOTAL,
    ATTR_CHARGE_ENERGY_TODAY,
    ATTR_CHARGE_ENERGY_TOTAL,
    ATTR_PAC_TO_GRID_TOTAL,
    ATTR_PAC_TO_USER_TOTAL,
)
from ..API.device_type.storage_120 import (
    STORAGE_PRIORITY_MODE_CODES,
    ChargeDischargeMode,
)

STORAGE_SWITCH_TYPES: tuple[GrowattSwitchEntityDescription, ...] = (
    GrowattSwitchEntityDescription(
        key=ATTR_AC_CHARGE_ENABLED,
        name="AC Charge",
        entity_category=EntityCategory.CONFIG,
        state_on=0x1,
        state_off=0x0
    ),
    GrowattSwitchEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_1,
        name="Charge/Discharge Period 1 Enable",
        entity_category=EntityCategory.CONFIG,
        state_on=0x1,
        state_off=0x0,
        charge_discharge_period_enable = True,
    ),
    GrowattSwitchEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_2,
        name="Charge/Discharge Period 2 Enable",
        entity_category=EntityCategory.CONFIG,
        state_on=0x1,
        state_off=0x0,
        charge_discharge_period_enable = True,
    ),
    GrowattSwitchEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_3,
        name="Charge/Discharge Period 3 Enable",
        entity_category=EntityCategory.CONFIG,
        state_on=0x1,
        state_off=0x0,
        charge_discharge_period_enable = True,
    ),
    GrowattSwitchEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_4,
        name="Charge/Discharge Period 4 Enable",
        entity_category=EntityCategory.CONFIG,
        state_on=0x1,
        state_off=0x0,
        charge_discharge_period_enable = True,
    ),
    GrowattSwitchEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_5,
        name="Charge/Discharge Period 5 Enable",
        entity_category=EntityCategory.CONFIG,
        state_on=0x1,
        state_off=0x0,
        charge_discharge_period_enable = True,
    ),
    GrowattSwitchEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_6,
        name="Charge/Discharge Period 6 Enable",
        entity_category=EntityCategory.CONFIG,
        state_on=0x1,
        state_off=0x0,
        charge_discharge_period_enable = True,
    ),
    GrowattSwitchEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_7,
        name="Charge/Discharge Period 7 Enable",
        entity_category=EntityCategory.CONFIG,
        state_on=0x1,
        state_off=0x0,
        charge_discharge_period_enable = True,
    ),
    GrowattSwitchEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_8,
        name="Charge/Discharge Period 8 Enable",
        entity_category=EntityCategory.CONFIG,
        state_on=0x1,
        state_off=0x0,
        charge_discharge_period_enable = True,
    ),
    GrowattSwitchEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_9,
        name="Charge/Discharge Period 9 Enable",
        entity_category=EntityCategory.CONFIG,
        state_on=0x1,
        state_off=0x0,
        charge_discharge_period_enable = True,
    ),
)

STORAGE_SELECT_TYPES: tuple[GrowattSelectEntityDescription, ...] = (
    GrowattSelectEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_1,
        name="Charge/Discharge Period 1 Mode",
        entity_category=EntityCategory.CONFIG,
        options=list(ChargeDischargeMode),
        icon="mdi:battery-clock",
        value_to_state_dict={},
        charge_discharge_period_mode= True,
    ),
    GrowattSelectEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_2,
        name="Charge/Discharge Period 2 Mode",
        entity_category=EntityCategory.CONFIG,
        options=list(ChargeDischargeMode),
        icon="mdi:battery-clock",
        value_to_state_dict={},
        charge_discharge_period_mode= True,
    ),
    GrowattSelectEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_3,
        name="Charge/Discharge Period 3 Mode",
        entity_category=EntityCategory.CONFIG,
        options=list(ChargeDischargeMode),
        icon="mdi:battery-clock",
        value_to_state_dict={},
        charge_discharge_period_mode= True,
    ),
    GrowattSelectEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_4,
        name="Charge/Discharge Period 4 Mode",
        entity_category=EntityCategory.CONFIG,
        options=list(ChargeDischargeMode),
        icon="mdi:battery-clock",
        value_to_state_dict={},
        charge_discharge_period_mode= True,
    ),
    GrowattSelectEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_5,
        name="Charge/Discharge Period 5 Mode",
        entity_category=EntityCategory.CONFIG,
        options=list(ChargeDischargeMode),
        icon="mdi:battery-clock",
        value_to_state_dict={},
        charge_discharge_period_mode= True,
    ),
    GrowattSelectEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_6,
        name="Charge/Discharge Period 6 Mode",
        entity_category=EntityCategory.CONFIG,
        options=list(ChargeDischargeMode),
        icon="mdi:battery-clock",
        value_to_state_dict={},
        charge_discharge_period_mode= True,
    ),
    GrowattSelectEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_7,
        name="Charge/Discharge Period 7 Mode",
        entity_category=EntityCategory.CONFIG,
        options=list(ChargeDischargeMode),
        icon="mdi:battery-clock",
        value_to_state_dict={},
        charge_discharge_period_mode= True,
    ),
    GrowattSelectEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_8,
        name="Charge/Discharge Period 8 Mode",
        entity_category=EntityCategory.CONFIG,
        options=list(ChargeDischargeMode),
        icon="mdi:battery-clock",
        value_to_state_dict={},
        charge_discharge_period_mode= True,
    ),
    GrowattSelectEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_9,
        name="Charge/Discharge Period 9 Mode",
        entity_category=EntityCategory.CONFIG,
        options=list(ChargeDischargeMode),
        icon="mdi:battery-clock",
        value_to_state_dict={},
        charge_discharge_period_mode= True,
    ),
)

STORAGE_NUMBER_TYPES: tuple[GrowattNumberEntityDescription, ...] = (
    GrowattNumberEntityDescription(
        key=ATTR_DISCHARGE_POWER_LIMIT_RATE,
        name="Discharge Power Limit Rate",
        entity_category=EntityCategory.CONFIG,
        device_class=NumberDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        native_min_value=0,
        native_max_value=100,
        native_step=1,
        mode=NumberMode.AUTO,
        icon="mdi:battery-arrow-down",
    ),
    GrowattNumberEntityDescription(
        key=ATTR_CHARGE_POWER_LIMIT_RATE,
        name="Charge Power Limit Rate",
        entity_category=EntityCategory.CONFIG,
        device_class=NumberDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        native_min_value=0,
        native_max_value=100,
        native_step=1,
        mode=NumberMode.AUTO,
        icon="mdi:battery-arrow-up",
    ),
    GrowattNumberEntityDescription(
        key=ATTR_DISCHARGE_STOP_SOC_PERCENT_OFFGRID,
        name="Discharge Stop SOC Percentage (Off-grid)",
        entity_category=EntityCategory.CONFIG,
        device_class=NumberDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        native_min_value=10,
        native_max_value=100,
        native_step=1,
        mode=NumberMode.BOX,
        icon="mdi:battery-negative",
    ),
    GrowattNumberEntityDescription(
        key=ATTR_DISCHARGE_STOP_SOC_PERCENT_ONGRID,
        name="Discharge Stop SOC Percentage (On-grid)",
        entity_category=EntityCategory.CONFIG,
        device_class=NumberDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        native_min_value=10,
        native_max_value=100,
        native_step=1,
        mode=NumberMode.BOX,
        icon="mdi:battery-negative",
    ),
    GrowattNumberEntityDescription(
        key=ATTR_CHARGE_STOP_SOC_PERCENT,
        name="Charge Stop SOC Percentage",
        entity_category=EntityCategory.CONFIG,
        device_class=NumberDeviceClass.POWER_FACTOR,
        native_unit_of_measurement=PERCENTAGE,
        native_min_value=11,
        native_max_value=100,
        native_step=1,
        mode=NumberMode.BOX,
        icon="mdi:battery-positive",
    ),
)

STORAGE_TIME_TYPES: tuple[GrowattTimeEntityDescription, ...] = (
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_1,
        name="Charge/Discharge Period 1 Start Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_starttime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_1,
        name="Charge/Discharge Period 1 End Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_endtime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_2,
        name="Charge/Discharge Period 2 Start Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_starttime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_2,
        name="Charge/Discharge Period 2 End Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_endtime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_3,
        name="Charge/Discharge Period 3 Start Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_starttime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_3,
        name="Charge/Discharge Period 3 End Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_endtime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_4,
        name="Charge/Discharge Period 4 Start Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_starttime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_4,
        name="Charge/Discharge Period 4 End Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_endtime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_5,
        name="Charge/Discharge Period 5 Start Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_starttime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_5,
        name="Charge/Discharge Period 5 End Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_endtime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_6,
        name="Charge/Discharge Period 6 Start Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_starttime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_6,
        name="Charge/Discharge Period 6 End Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_endtime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_7,
        name="Charge/Discharge Period 7 Start Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_starttime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_7,
        name="Charge/Discharge Period 7 End Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_endtime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_8,
        name="Charge/Discharge Period 8 Start Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_starttime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_8,
        name="Charge/Discharge Period 8 End Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_endtime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_9,
        name="Charge/Discharge Period 9 Start Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_starttime = True,
    ),
    GrowattTimeEntityDescription(
        key=ATTR_CHARGE_DISCHARGE_PERIOD_9,
        name="Charge/Discharge Period 9 End Time",
        entity_category=EntityCategory.CONFIG,
        icon="mdi:battery-clock",
        charge_discharge_period_endtime = True,
    ),
)

STORAGE_SENSOR_TYPES: tuple[GrowattSensorEntityDescription, ...] = (
    GrowattSensorEntityDescription(
        key=ATTR_PRIORITY_MODE,
        name="Priority Mode",
        device_class=SensorDeviceClass.ENUM,
        options=list(STORAGE_PRIORITY_MODE_CODES.values()),
    ),
    GrowattSensorEntityDescription(
        key=ATTR_SOC_PERCENTAGE,
        name="SOC",
        native_unit_of_measurement=PERCENTAGE,
        device_class=SensorDeviceClass.BATTERY,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    GrowattSensorEntityDescription(
        key=ATTR_DISCHARGE_POWER,
        name="Discharge Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    GrowattSensorEntityDescription(
        key=ATTR_CHARGE_POWER,
        name="Charge Power",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    GrowattSensorEntityDescription(
        key=ATTR_POWER_TO_USER,
        name="Power to user",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    GrowattSensorEntityDescription(
        key=ATTR_POWER_TO_GRID,
        name="Power to grid",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    GrowattSensorEntityDescription(
        key=ATTR_POWER_USER_LOAD,
        name="Power user load",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    GrowattSensorEntityDescription(
        key=ATTR_ENERGY_TO_GRID_TOTAL,
        name="Energy To Grid (Total)",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    GrowattSensorEntityDescription(
        key=ATTR_ENERGY_TO_GRID_TODAY,
        name="Energy To Grid (Today)",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        midnight_reset=True
    ),
    GrowattSensorEntityDescription(
        key=ATTR_ENERGY_TO_USER_TOTAL,
        name="Energy To User (Total)",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),

    GrowattSensorEntityDescription(
        key=ATTR_ENERGY_TO_USER_TODAY,
        name="Energy To User (Today)",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        midnight_reset=True
    ),
    GrowattSensorEntityDescription(
        key=ATTR_DISCHARGE_ENERGY_TODAY,
        name="Battery Discharged (Today)",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        midnight_reset=True
    ),
    GrowattSensorEntityDescription(
        key=ATTR_DISCHARGE_ENERGY_TOTAL,
        name="Battery Discharged (Total)",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    GrowattSensorEntityDescription(
        key=ATTR_CHARGE_ENERGY_TODAY,
        name="Battery Charged (Today)",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
        midnight_reset=True
    ),
    GrowattSensorEntityDescription(
        key=ATTR_CHARGE_ENERGY_TOTAL,
        name="Battery Charged (Total)",
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        device_class=SensorDeviceClass.ENERGY,
        state_class=SensorStateClass.TOTAL_INCREASING,
    ),
    GrowattSensorEntityDescription(
        key=ATTR_PAC_TO_USER_TOTAL,
        name="AC to user total",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
    GrowattSensorEntityDescription(
        key=ATTR_PAC_TO_GRID_TOTAL,
        name="AC to grid total",
        native_unit_of_measurement=UnitOfPower.WATT,
        device_class=SensorDeviceClass.POWER,
        state_class=SensorStateClass.MEASUREMENT,
    ),
)
